name: 'Install Dependencies'
description: 'Installs from the Gemfile and Podfile'
runs:
  using: composite
  steps:
    - uses: actions/cache@v2
      with:
        path: |
          Pods
          Tools/MaterialDesignIcons.ttf
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock', 'Tools/BuildMaterialDesignIconsFont.sh') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install Gems
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Install Pods
      run: diff Pods/Manifest.lock Podfile.lock >/dev/null || bundle exec pod install --repo-update
