name: Download Localized Strings
on:
  workflow_dispatch:

jobs:
  update_strings:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/dependencies
        name: Install Dependencies
      - name: Download from Lokalise
        run: bundle exec fastlane update_strings
        env:
          HOMEASSISTANT_LOKALIZE_PROJECT_ID: ${{ secrets.HOMEASSISTANT_LOKALIZE_PROJECT_ID }}
          HOMEASSISTANT_LOKALIZE_TOKEN: ${{ secrets.HOMEASSISTANT_LOKALIZE_TOKEN }}
      - name: Commit changes
        run: |
          git config --global user.name 'Home Assistant Bot'
          git config --global user.email 'hello@home-assistant.io'
          git commit -am "Update Localized Strings"
          git push
