name: CI

on:
  pull_request:

env:
  FASTLANE_SKIP_UPDATE_CHECK: true
  FASTLANE_XCODE_LIST_TIMEOUT: 30
  MATCH_KEYCHAIN_NAME: "gh_actions"

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run fastlane setup
      run: |
        fastlane ios test --verbose
